### ISSUE TITLE
Fix (eos_designs) correct error if missing node

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1877]
### Issue Summary

Expect to see an AristaAvdMissingVariableError, but get an UnboundLocalError: local variable 'node_config' referenced before assignment due to variable going out of scope

https://github.com/pvinci-arista/ansible-avd/blob/devel/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py#L334

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Relevant log output

```shell
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 589, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/action/eos_designs_facts.py", line 57, in run
    avd_switch_facts = self.render_avd_switch_facts(avd_switch_facts_instances)
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/action/eos_designs_facts.py", line 145, in render_avd_switch_facts
    rendered_facts[host] = {"switch": avd_switch_facts_instances[host]['switch'].render()}
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py", line 79, in render
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py", line 79, in <dictcomp>
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py", line 555, in always_include_vrfs_in_tenants
    return get(self._switch_data_combined, "filter.always_include_vrfs_in_tenants")
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py", line 352, in _switch_data_combined
    return get(self._switch_data, "combined", required=True)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/pvinci/.ansible/collections/ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py", line 334, in _switch_data
    if not node_config:
UnboundLocalError: local variable 'node_config' referenced before assignment
fatal: [OOB_MGMTA]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
resolved by #1827
