### ISSUE TITLE
l2leaf affected by rfc5549 evpn settings

### ISSUE THREAD

**Issue by bfhsimon** [aristanetworks/ansible-avd#2954]
### Issue Summary

We upgrade from v3.7.0 to devel branch and get the error:

```
Error message in "TASK [Arista.avd.eos_designs : Set eos_designs facts]":
(...)
'overlay_routing_protocol_address_family: ipv6' is only supported in
combination with 'underlay_ipv6: True' and 'underlay_rfc5549: True'
```
We have set the following for all hosts:

```
underlay_ipv6: true
underlay_rfc5549: true
overlay_routing_protocol_address_family: 'ipv6'
```

The problem is related to l2leafs: if I set the following for all
l2leafs, the error disappears:

```
overlay_routing_protocol_address_family: ipv4
```

I would have expected that l2leafs ignore all evpn related settings.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Relevant log output

```shell
TASK [arista.avd.eos_designs : Set eos_designs facts] ************************************************************************************************
task path: /home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/roles/eos_designs/tasks/main.yml:26
Wednesday 24 May 2023  12:46:38 +0000 (0:00:00.429)       0:00:00.693 ********* 
Wednesday 24 May 2023  12:46:38 +0000 (0:00:00.429)       0:00:00.693 ********* 
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 633, in _execute
    result = self._handler.run(task_vars=vars_copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/action/eos_designs_facts.py", line 63, in run
    avd_switch_facts = self.render_avd_switch_facts(avd_switch_facts_instances)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/action/eos_designs_facts.py", line 188, in render_avd_switch_facts
    rendered_facts[host] = {"switch": avd_switch_facts_instances[host]["switch"].render()}
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in render
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/plugin_utils/avdfacts.py", line 64, in <dictcomp>
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
                                                              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_facts/overlay.py", line 64, in overlay
    "peering_address": self.shared_utils.overlay_peering_address,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_shared_utils/overlay.py", line 157, in overlay_peering_address
    if self.overlay_routing_protocol_address_family == "ipv6":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/network/ansible/ansible-avd-4/ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_shared_utils/overlay.py", line 86, in overlay_routing_protocol_address_family
    raise AristaAvdError(
ansible_collections.arista.avd.plugins.plugin_utils.errors.errors.AristaAvdError: 'overlay_routing_protocol_address_family: ipv6' is only supported in combination with 'underlay_ipv6: True' and 'underlay_rfc5549: True'
fatal: [edge1.rack4.fabric-b.brn-enge12.bfh.network]: FAILED! => 
  msg: 'Unexpected failure during module execution: ''overlay_routing_protocol_address_family: ipv6'' is only supported in combination with ''underlay_ipv6: True'' and ''underlay_rfc5549: True'''
  stdout: ''
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@bfhsimon Thank you for reporting this issue.

I have submitted a fix which we will merge in time for 4.0.0-rc3. I could also recreate this issue in AVD v3.8.6, so we will back port it to 3.8.x as well.

Thanks again, your feedback is highly appreciated.
