### ISSUE TITLE
pyAVD failing due to dependency on pyyaml

### ISSUE THREAD

**Issue by SolidFort** [aristanetworks/ansible-avd#3834]
### Issue Summary

Using pyAVD in a script results in tracebacks due to pyAVD's dependency on pyyaml.
It would be beneficial to have the pyyaml module included as part of the pyAVD installation process.

### Which component(s) of AVD impacted

others

### How do you run AVD ?

None

### Steps to reproduce

```shell
1) install python3 on a server
2) install pyavd on the server using "pip3 install pyavd"
3) import pyavd in a script and run the script.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/vendor/utils/yaml_dumper.py", line 7, in <module>
    from yaml import CSafeDumper as YamlDumper
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Automation/Scripts/onewan/main.py", line 1, in <module>
    import pyavd
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/__init__.py", line 4, in <module>
    from .get_avd_facts import get_avd_facts
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/get_avd_facts.py", line 6, in <module>
    from .vendor.eos_designs.eos_designs_facts import EosDesignsFacts
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/vendor/eos_designs/eos_designs_facts/__init__.py", line 4, in <module>
    from .eos_designs_facts import EosDesignsFacts
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/vendor/eos_designs/eos_designs_facts/eos_designs_facts.py", line 10, in <module>
    from pyavd.vendor.utils import get
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/vendor/utils/__init__.py", line 26, in <module>
    from .yaml_dumper import NoAliasDumper, YamlDumper
  File "~/Library/Python/3.10/lib/python/site-packages/pyavd/vendor/utils/yaml_dumper.py", line 9, in <module>
    from yaml import SafeDumper as YamlDumper
ModuleNotFoundError: No module named 'yaml'
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting this.
Indeed we should handle this, but the underlying issue is actually that PyAVD should not include those `yaml_dumper`, `yaml_loader` modules vendored in from ansible-avd. I will address that, so we will not rely on PyYAML.

Thanks again.
Claus
