### ISSUE TITLE
Better handling of index error p2p_links nodes and other fields in core_interface / l3_edge schema

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#4727]
```
  p2p_links:
    # Pe_P
    - nodes: [pe11-sav366, p11-brv350, pe11-sav366, p12-brv350]
      interfaces: [Ethernet43/1, Ethernet1/1, Ethernet44/1, Ethernet1/1]
      profile: pe_p_profile
      id: 1
```

This is accepted but fails sadly 

```
The full traceback is:
Traceback (most recent call last):
  File "/home/arista/.ansible/collections/ansible_collections/arista/avd/plugins/action/eos_designs_structured_config.py", line 100, in run
    output = get_structured_config(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/structured_config/__init__.py", line 96, in get_structured_config
    results = eos_designs_module.render()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/structured_config/core_interfaces_and_l3_edge/__init__.py", line 40, in render
    result_list.append(super().render())
                       ^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/avdfacts.py", line 64, in render
    return {key: getattr(self, key) for key in self.keys() if getattr(self, key) is not None}
                                                              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/structured_config/core_interfaces_and_l3_edge/ethernet_interfaces.py", line 30, in ethernet_interfaces
    for p2p_link in self._filtered_p2p_links:
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/structured_config/core_interfaces_and_l3_edge/utils.py", line 67, in _filtered_p2p_links
    [p2p_link.update({"data": self._get_p2p_data(p2p_link)}) for p2p_link in p2p_links]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arista/.local/share/pipx/venvs/pyavd/lib/python3.12/site-packages/pyavd/_eos_designs/structured_config/core_interfaces_and_l3_edge/utils.py", line 146, in _get_p2p_data
    "ip": ip[index],
          ~~^^^^^^^
IndexError: list index out of range
fatal: [p22-qzd516 -> localhost]: FAILED! => {
    "changed": false,
    "msg": "list index out of range"
}
```

First idea was to limit the llength in the list

**Comment by gmuloc** [comment]
Catch ip index and indicate that`ip_pools` cannot allocate more than 2 ips but it can be done manually.
