### ISSUE TITLE
device_filter list for arista.avd.eos_config_deploy_cvp

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#506]
## Issue Type

- Bug Report

## Summary

The device_filter for arista.avd.eos_config_deploy_cvp is just accepting one string but not multiple values to filter more exactly.

## Role or Module Name
arista.avd.eos_config_deploy_cvp

## Steps to reproduce

```yaml
---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: no

  tasks:

    - name: include global_vars
      tags: [build, provision]
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/DC_LAB.yml"
        - "../global_vars/EOS.yml"

    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_l3ls_evpn

    - name: generate intented DCI variables
      tags: [build, provision]
      import_role:
         name: eos_dci

    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP-1
  connection: local
  gather_facts: no

  tasks:

#    - name: upload cvp configlets
#      import_role:
#          name: arista.avd.cvp_configlet_upload
#      vars:
#        configlets_cvp_prefix: 'RS'
#        configlet_directory: "{{inventory_dir}}/configlets"

    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC_FABRIC'
        configlets_prefix: 'DC1'
        device_filter: 
           -  '-2'
           - '-11E'
           - '-11F2-002'
        state: present
```

### Expected results

```shell
$
```

### Actual results

```shell
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'in <string>' requires string as left operand, not list
fatal: [CVP-1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.avd.plugins.modules.inventory_to_container', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 421, in <module>
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 404, in main
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 367, in get_containers
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      [Previous line repeated 2 more times]
     File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 311, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 145, in is_in_filter
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 145, in <genexpr>
    TypeError: 'in <string>' requires string as left operand, not list
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

<!--- Paste verbatim command output between quotes below -->
```

**Comment by titom73** [comment]
Hello @kmueller68 

Indeed `device_filter` available in `arista.avd.eos_config_deploy_cvp` only supports a string [as stated in documentation](https://www.avd.sh/en/latest/roles/eos_config_deploy_cvp/) and does not support list

So in the task file, it is considered `device_filter` as a string so raise an error when you sent a list.

```yaml
# Common action for all states.
- name: generate intented variables
  tags: [always]
  arista.avd.inventory_to_container:
    inventory: '{{ inventory_file }}'
    container_root: '{{ container_root }}'
    configlet_dir: '{{ root_dir }}/intended/configs'
    configlet_prefix: '{{ configlets_prefix }}'
    destination: '{{ root_dir }}/intended/structured_configs/cvp/{{ inventory_hostname }}_configlets.yml'
    device_filter: ['{{ device_filter }}']
```

Since the `inventory_to_container` module supports the list for the filter, we will see what are the impact of changing default behavior in the next versions.

**Comment by kmueller68** [comment]
Hello. 
Thank you very much for looking at this request.

**Comment by titom73** [comment]
Hello @kmueller68 

A draft PR #660 has been submitted and you can test and comment if it is working for you as well

Please feel free to test and report
